# Generated by Django 5.1.1 on 2024-10-29 17:48

import cloudinary.models
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('background_color', models.CharField(choices=[('#FFE5F8', 'Pink'), ('#DBF0DB', 'Green'), ('#DAD6FF', 'Purple'), ('#FFEEBE', 'Yellow'), ('#FFFDEB', 'Cream'), ('#FFD9CE', 'Peach'), ('#D3EDFE', 'Blue'), ('#C8F6F6', 'Ocean')], default='#FFE5F8', max_length=10)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
