# Generated by Django 5.1.1 on 2024-10-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_alter_build_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='build',
            name='status',
            field=models.CharField(default='active', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='type',
            field=models.CharField(default='type1', max_length=255),
            preserve_default=False,
        ),
    ]
