# Generated by Django 5.1.2 on 2024-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_build_courses_build_experts_build_mechanisms'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
