# Generated by Django 5.1.2 on 2024-11-01 19:07

from django.db import migrations

def set_hidden_false(apps, schema_editor):
    Build = apps.get_model('builds', 'Build')
    Build.objects.filter(hidden__isnull=True).update(hidden=False)



class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_hidden'),
    ]

    operations = [
        migrations.RunPython(set_hidden_false),
    ]
