# Generated by Django 5.1.2 on 2024-11-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20241101_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='builds',
            field=models.ManyToManyField(blank=True, to='builds.build'),
        ),
    ]
