# Generated by Django 5.1.2 on 2024-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_build_builds'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='related_builds', to='categories.category'),
        ),
    ]
