# Generated by Django 5.1.2 on 2024-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0007_build_builds'),
        ('courses', '0005_course_courses'),
        ('experts', '0015_expert_experts'),
        ('mechanisms', '0014_mechanism_mechanisms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builds', models.ManyToManyField(blank=True, related_name='related_categories', to='builds.build')),
                ('courses', models.ManyToManyField(blank=True, related_name='related_categories', to='courses.course')),
                ('experts', models.ManyToManyField(blank=True, related_name='related_categories', to='experts.expert')),
                ('mechanisms', models.ManyToManyField(blank=True, related_name='related_categories', to='mechanisms.mechanism')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
