# Generated by Django 5.1.2 on 2024-11-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_build_courses_build_experts_build_mechanisms'),
        ('courses', '0001_initial'),
        ('experts', '0012_alter_expert_builds_alter_expert_courses'),
        ('mechanisms', '0009_mechanism_builds_mechanism_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='builds',
            field=models.ManyToManyField(blank=True, related_name='related_courses', to='builds.build'),
        ),
        migrations.AddField(
            model_name='course',
            name='experts',
            field=models.ManyToManyField(blank=True, related_name='related_courses', to='experts.expert'),
        ),
        migrations.AddField(
            model_name='course',
            name='mechanisms',
            field=models.ManyToManyField(blank=True, related_name='related_courses', to='mechanisms.mechanism'),
        ),
    ]
