# Generated by Django 5.1.2 on 2024-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_builds_course_experts_course_mechanisms'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
