# Generated by Django 5.1.2 on 2024-11-01 19:06

from django.db import migrations

def set_hidden_false(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Course.objects.filter(hidden__isnull=True).update(hidden=False)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_hidden'),
    ]

    operations = [
        migrations.RunPython(set_hidden_false),
    ]
