# Generated by Django 5.1.2 on 2024-11-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20241101_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
