# Generated by Django 5.1.1 on 2024-09-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanism',
            old_name='logo',
            new_name='background_img',
        ),
        migrations.AddField(
            model_name='mechanism',
            name='background_color',
            field=models.CharField(choices=[('#FFE5F8', 'Pink'), ('#DBF0DB', 'Green'), ('#DAD6FF', 'Purple'), ('#FFEEBE', 'Yellow'), ('#FFFDEB', 'Cream'), ('#FFD9CE', 'Peach'), ('#D3EDFE', 'Blue'), ('#C8F6F6', 'Ocean')], default='#FFE5F8', max_length=10),
        ),
    ]
