# Generated by Django 5.1.1 on 2024-09-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0002_rename_logo_mechanism_background_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
