# Generated by Django 5.1.1 on 2024-09-19 22:34

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0003_alter_mechanism_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
