# Generated by Django 5.1.1 on 2024-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0004_alter_mechanism_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
