# Generated by Django 5.1.2 on 2024-11-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0006_mechanism_related_build_mechanism_related_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanism',
            name='related_build',
        ),
        migrations.RemoveField(
            model_name='mechanism',
            name='related_course',
        ),
        migrations.RemoveField(
            model_name='mechanism',
            name='related_expert',
        ),
    ]
