# Generated by Django 5.1.2 on 2024-11-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0011_alter_expert_mechanisms'),
        ('mechanisms', '0007_remove_mechanism_related_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='experts',
            field=models.ManyToManyField(blank=True, related_name='related_mechanisms', to='experts.expert'),
        ),
    ]
