# Generated by Django 5.1.2 on 2024-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_metadata_build_status_build_type'),
        ('courses', '0001_initial'),
        ('mechanisms', '0008_mechanism_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='builds',
            field=models.ManyToManyField(blank=True, related_name='related_mechanisms', to='builds.build'),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='related_mechanisms', to='courses.course'),
        ),
    ]
