# Generated by Django 5.1.2 on 2024-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0009_mechanism_builds_mechanism_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
