# Generated by Django 5.1.2 on 2024-11-01 19:04

from django.db import migrations

def set_hidden_false(apps, schema_editor):
    Mechanism = apps.get_model('mechanisms', 'Mechanism')
    Mechanism.objects.filter(hidden__isnull=True).update(hidden=False)


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0010_mechanism_hidden'),
    ]

    operations = [
        migrations.RunPython(set_hidden_false),
    ]
