# Generated by Django 5.1.2 on 2024-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20241101_1906'),
        ('mechanisms', '0011_auto_20241101_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='related_courses', to='courses.course'),
        ),
    ]
