# Generated by Django 5.1.2 on 2024-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanisms', '0013_alter_mechanism_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='mechanisms',
            field=models.ManyToManyField(blank=True, to='mechanisms.mechanism'),
        ),
    ]
