# Generated by Django 5.1.2 on 2024-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('mechanisms', '0014_mechanism_mechanisms'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='related_mechanisms', to='categories.category'),
        ),
    ]
