# Generated by Django 5.1.1 on 2024-09-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='logo',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='expert',
            old_name='email',
            new_name='contact_info_email',
        ),
        migrations.AddField(
            model_name='expert',
            name='contact_info_telegram',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='contact_info_twitter',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='expert_in',
            field=models.CharField(choices=[('allo_mechanisms', 'Allo Mechanisms'), ('allo_dev', 'Allo Dev')], default='allo_mechanisms', max_length=40),
        ),
        migrations.AddField(
            model_name='expert',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
