# Generated by Django 5.1.1 on 2024-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_rename_logo_expert_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expert_in',
            field=models.CharField(choices=[('allo_Experts', 'Allo Experts'), ('allo_dev', 'Allo Dev')], default='allo_Experts', max_length=40),
        ),
    ]
