# Generated by Django 5.1.2 on 2024-11-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_relatedobject_expert'),
        ('mechanisms', '0007_remove_mechanism_related_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedobject',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experts.expert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedobject',
            name='mechanism',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mechanisms.mechanism'),
            preserve_default=False,
        ),
    ]
