# Generated by Django 5.1.2 on 2024-11-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_metadata_build_status_build_type'),
        ('courses', '0001_initial'),
        ('experts', '0006_expert_mechanisms'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedobject',
            name='build',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='builds.build'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedobject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
