# Generated by Django 5.1.2 on 2024-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('experts', '0007_relatedobject_build_relatedobject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='experts', to='courses.course'),
        ),
    ]
