# Generated by Django 5.1.2 on 2024-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_metadata_build_status_build_type'),
        ('experts', '0008_expert_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='builds',
            field=models.ManyToManyField(blank=True, related_name='experts', to='builds.build'),
        ),
    ]
