# Generated by Django 5.1.2 on 2024-11-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0009_expert_builds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedObject',
        ),
    ]
