# Generated by Django 5.1.2 on 2024-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_build_courses_build_experts_build_mechanisms'),
        ('courses', '0001_initial'),
        ('experts', '0011_alter_expert_mechanisms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='builds',
            field=models.ManyToManyField(blank=True, related_name='related_experts', to='builds.build'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='related_experts', to='courses.course'),
        ),
    ]
