# Generated by Django 5.1.2 on 2024-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0012_alter_expert_builds_alter_expert_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
