# Generated by Django 5.1.2 on 2024-11-01 19:02

from django.db import migrations

def set_hidden_false(apps, schema_editor):
    Expert = apps.get_model('experts', 'Expert')
    Expert.objects.filter(hidden__isnull=True).update(hidden=False)


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0013_expert_hidden'),
    ]

    operations = [
        migrations.RunPython(set_hidden_false),
    ]
