# Generated by Django 5.1.2 on 2024-11-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0014_auto_20241101_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='experts',
            field=models.ManyToManyField(blank=True, to='experts.expert'),
        ),
    ]
