# Generated by Django 5.1.2 on 2024-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('experts', '0015_expert_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='related_experts', to='categories.category'),
        ),
    ]
